// Generated by ../dtln/sync-to-awful.mjs ("npm run sync" there) - do not edit.
// The ?v= content hash makes the service worker treat each worklet build
// as a new cache entry instead of serving the first one forever.
export const WORKLET_URL = "/audio-worklet.js?v=844c74a2";
