/**
 * Regenerates the npm section of public/third-party-notices.txt.
 *
 * The file's link in the app promises "full license texts for bundled code";
 * before this script it carried only the hand-written DTLN worklet notices,
 * while the JS bundle ships hundreds of MIT/Apache/BSD packages whose
 * licenses require their notices to travel with distributed copies.
 *
 * Everything above the marker line is hand-maintained (the DTLN wasm story);
 * everything below is generated from the packages' own LICENSE files,
 * deduplicated by identical text so the stock MIT text appears once with
 * every package that uses it listed above it.
 *
 * Sources, in order: `pnpm licenses` (prod-only, needs the pnpm store index,
 * available locally), else a direct walk of node_modules/.pnpm (works in
 * docker builds where the store index is not copied; includes dev packages,
 * which over-attributes and never under-attributes). NEVER fails the build:
 * the committed file from the last successful run ships as-is.
 */
import { execSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "third-party-notices.txt");
const MARKER =
  "================ GENERATED NPM LICENSE NOTICES BELOW - do not edit ================";

function licenseText(pkgPath) {
  let entries;
  try {
    entries = readdirSync(pkgPath);
  } catch {
    return null;
  }
  const match = entries.find((f) =>
    /^(licen[cs]e|copying|notice)(\.|$)/i.test(f)
  );
  if (!match) return null;
  try {
    return readFileSync(join(pkgPath, match), "utf8").trim();
  } catch {
    return null;
  }
}

/** [{name, license, homepage, path}] via pnpm (prod dependencies only). */
function viaPnpm() {
  const raw = execSync("pnpm licenses list --prod --json", {
    cwd: root,
    maxBuffer: 64 * 1024 * 1024,
    stdio: ["ignore", "pipe", "ignore"],
  }).toString();
  const byLicense = JSON.parse(raw);
  const out = [];
  for (const [license, pkgs] of Object.entries(byLicense)) {
    for (const p of pkgs) {
      out.push({
        name: p.name,
        license,
        homepage: p.homepage,
        path: p.paths?.[0] ?? "",
      });
    }
  }
  return { pkgs: out, scope: "production npm packages" };
}

/** Fallback: walk node_modules/.pnpm/<id>/node_modules/<pkg> directly. */
function viaWalk() {
  const store = join(root, "node_modules", ".pnpm");
  const out = [];
  const seen = new Set();
  for (const id of readdirSync(store)) {
    const nm = join(store, id, "node_modules");
    if (!existsSync(nm)) continue;
    for (const top of readdirSync(nm)) {
      const dirs = top.startsWith("@")
        ? readdirSync(join(nm, top)).map((s) => join(nm, top, s))
        : [join(nm, top)];
      for (const dir of dirs) {
        let pkg;
        try {
          pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
        } catch {
          continue;
        }
        const key = `${pkg.name}@${pkg.version}`;
        if (!pkg.name || seen.has(key)) continue;
        seen.add(key);
        const license =
          typeof pkg.license === "string"
            ? pkg.license
            : (pkg.license?.type ?? "see package");
        out.push({
          name: pkg.name,
          license,
          homepage: pkg.homepage,
          path: dir,
        });
      }
    }
  }
  return { pkgs: out, scope: "npm packages present in the build environment" };
}

try {
  let result;
  try {
    if (process.env.NOTICES_NO_PNPM) throw new Error("forced fallback");
    result = viaPnpm();
  } catch {
    console.warn("[notices] pnpm licenses unavailable, walking node_modules");
    result = viaWalk();
  }

  const byText = new Map();
  const missing = [];
  for (const p of result.pkgs) {
    const text = licenseText(p.path);
    const entry = `${p.name} (${p.license})`;
    if (!text) {
      missing.push(entry + (p.homepage ? ` - ${p.homepage}` : ""));
      continue;
    }
    const bucket = byText.get(text) ?? [];
    bucket.push(entry);
    byText.set(text, bucket);
  }

  const sections = [...byText.entries()]
    .sort((a, b) => b[1].length - a[1].length)
    .map(([text, pkgs]) => {
      const head = [...new Set(pkgs)].sort().join("\n");
      return `${"-".repeat(80)}\n${head}\n${"-".repeat(80)}\n\n${text}\n`;
    });

  const generated = [
    MARKER,
    "",
    `The JavaScript bundle includes the following ${result.scope}. Identical`,
    `license texts are printed once, with every package that ships under that`,
    `exact text listed above it. Regenerated by scripts/generate-notices.mjs`,
    `from the packages' own LICENSE files at build time.`,
    "",
    ...sections,
    ...(missing.length
      ? [
          "-".repeat(80),
          "Packages whose tarball carries no license file (license identifier",
          "from their package.json; text available at the linked homepage):",
          "-".repeat(80),
          "",
          ...[...new Set(missing)].sort(),
          "",
        ]
      : []),
  ].join("\n");

  const current = readFileSync(OUT, "utf8");
  const markerAt = current.indexOf(MARKER);
  const head = (markerAt >= 0 ? current.slice(0, markerAt) : current).trimEnd();
  writeFileSync(OUT, head + "\n\n" + generated + "\n");
  console.log(
    `[notices] ${byText.size} unique license texts, ` +
      `${[...byText.values()].reduce((n, v) => n + v.length, 0)} packages, ` +
      `${missing.length} without a license file`
  );
} catch (err) {
  // The committed notices file from the last successful run ships as-is; a
  // license-text refresh is never worth a failed deploy.
  console.warn("[notices] generation failed, keeping committed file:", err);
}
